# Generated by Django 2.1.5 on 2019-02-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_no',
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_item',
            field=models.CharField(max_length=1200),
        ),
    ]
